version: "3.9" 

services:
  psql-db:
    image: postgres
    container_name: psql-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=summarize
    ports:
      - '5432:5432'


  transcript-service:
    build: ./transcript-service  
    ports:
      - "8000:8000"  
    volumes:
      - ./transcript-service:/app  # Mount your Django project directory within the container
    env_file:
      - transcript-service/.env

  frontend:
    build: ./frontend 
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app  
      - node_modules:/node_modules  

volumes:
  node_modules:
