version: "3.9" 

services:
  psql-db:
    image: postgres
    container_name: psql-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=summarize
    ports:
      - '5432:5432'

  server:
    image: server
    container_name: server
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - psql-db


  transcript-service:
    build: ./transcript-service  
    container_name: transcript_service
    ports:
      - "8000:8000"  
    volumes:
      - ./transcript-service:/app  # Mount your Django project directory within the container
    env_file:
      - transcript-service/.env

  frontend:
    container_name: frontend_app
    image: frontend:latest
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - server

