version: "3.9" 

services:
  transcript-service:
    build: ./transcript-service  # Build context for the backend service (replace with your Django project directory)
    ports:
      - "8000:8000"  # Map container port 8000 to host port 8000
    volumes:
      - ./transcript-service:/app  # Mount your Django project directory within the container
    environment:
      - PYTHONUNBUFFERED=1  # Fix Django output buffering issue

  # React frontend service
  frontend:
    build: ./frontend  # Build context for the frontend service (replace with your React project directory)
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app  # Mount your React project directory within the container
      - node_modules:/node_modules  # (Optional) Cache node_modules directory

volumes:
  # (Optional) Shared volume for node_modules (if used in frontend service)
  node_modules:
